#!/usr/bin/env python3

from os import read, write
import os, sys, tty, signal, termios

class BananaShell(object):
    def __init__(self, readline=None):
        BananaShell.validate_python_version()
        self.jobs = []
        self.readline = readline if readline else ReadlineFunctor()
        self.builtins = {}
        self.functions = {}

        self.configure_builtins()
    
    @staticmethod
    def validate_python_version():
        PY_MAJOR_VERSION = sys.version_info.major
        PY_MINOR_VERSION = sys.version_info.minor
    
        if not (PY_MAJOR_VERSION == 3 and PY_MINOR_VERSION >= 8):
            msg = f'Your python version is {PY_MAJOR_VERSION}.{PY_MINOR_VERSION}, please update to at least python 3.8!\n\n'
            raise InvalidPythonException(msg)

    def configure_builtins(self):
        for builtin in filter(lambda builtin: '_cmd_' in builtin, self.__dir__()):
            self.builtins[builtin.split('_cmd_')[1]] = eval('self.' + builtin)

    def _cmd_cd(self, args):
        try:
            # Simulate ZSH-like behavior
            if len(args) == 1 or args[-1] == '~':
                home = os.environ['HOME'] if 'HOME' in os.environ else '/'
                os.chdir(home)
                os.environ['PWD'] = home
                return
                
            path = args[-1]
            os.chdir(path)
            os.environ['PWD'] = args[-1]
            
        except Exception as error:
            os.write(2, f'cd: {error}\n'.encode())
        
    def _cmd_export(self, args):
        valid_ident = '_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
        
        try:
            key,val = ' '.join(args[1:]).split('=')
            if not key in valid_ident:
                raise Exception(f'not valid in this context: {key}')
            os.environ[key] = val
        except Exception as error:
            os.write(1, f'export: {error}\n'.encode())
            
    def _cmd_def(self, args):
        if args[2] == '{':
            readline = ReadlineFunctor()
            while (line := readline('')) not in (readline.eof, '}\n'):
                if line == '\n':
                    continue
                name = args[1]
                cmd = Command(line)
                self.functions[name] = self.functions[name] + [cmd] if name in self.functions else [cmd]

    def parse_function(self, func):
        for cmd in func:
            self.run(cmd)
                
    def run(self, directive):
        for cmd in directive:        
            if cmd.in_env():
                jid = len(self.jobs) + 1
                cmd.exec(self.jobs)
                continue
             
            try:
                self.parse_function(self.functions[cmd.name])
                return
            except KeyError:
                pass
            except IndexError:
                pass
             
            try:
                self.builtins[cmd.name](cmd.args)
            except KeyError:
                print(f'BananaShell: command not found: \'{cmd.name}\'')
                return

    def check_jobs(self):
        jobs = self.jobs.copy()
        for job in self.jobs:
            jid, pid, name = job
            try:
                os.waitpid(pid, os.WNOHANG)
                os.kill(pid, 0)
            except:
                os.write(1, f'[{jid}] {pid} terminated {name}\n'.encode())
                jobs.remove(job)
        self.jobs = jobs
        
        
    def __call__(self):
        while (line := self.readline(f'[{os.getcwd()}]\n$ ' if not 'PS1' in os.environ else os.environ['PS1'])) not in (self.readline.eof, 'exit\n'):
            self.check_jobs()
            if line == '\n':
                os.write(1,'\n'.encode())
                continue

            directive = Directive(line)
            self.run(directive)
            os.write(1,'\n'.encode())


class Directive(object):
    def __init__(self, line):
        self.files = []
        line = line.split('\n')[0]
        tokens = self.tokenize(line)
        self.commands = self.configure(tokens)

    def __iter__(self):
        return iter(self.commands)

    def tokenize(self, line, tokens=None):
        if not tokens:
            tokens = []
        for char in line:
            if char in ('|', '<', '>', '&'):
                idx = line.index(char)
                left = line[:idx]
                right = line[idx+1:]
                tokens += [left, char]
                return self.tokenize(right, tokens)
        tokens += [line]
        return [token for token in tokens if token != '']

    def configure(self, tokens):
        if not any(operator in tokens for operator in ('|', '<', '>', '&')):
            return [Command(tokens[0])]
        try:
            for idx, token in enumerate(tokens):
                if token == '|':
                    tokens[idx-1] = (left := Command(tokens[idx-1]))
                    tokens[idx+1] = (right := Command(tokens[idx+1]))
                    r, w = os.pipe()
                    os.set_inheritable(r,True)
                    os.set_inheritable(w,True)
                    left.iomap += [(w,1)]
                    right.iomap += [(r,0)]
                    self.files += [r,w]
                elif token == '>':
                    tokens[idx-1] = (left := Command(tokens[idx-1]))
                    tokens[idx+1] = (right := self.sanitize(tokens[idx+1]))
                    file_to = os.open(right, os.O_WRONLY | os.O_CREAT, 0o644)
                    left.iomap += [(file_to,1)]
                    self.files += [file_to]
                elif token == '<':
                    tokens[idx-1] = (left := Command(tokens[idx-1]))
                    tokens[idx+1] = (right := self.sanitize(tokens[idx+1]))
                    try:
                        file_from = os.open(right, os.O_RDONLY)
                    except FileNotFoundError as error:
                        os.write(1, f'cannot open file specified: {right}\n')
                    left.iomap += [(file_from,0)]
                    self.files += [file_from]
                elif token == '&':
                    tokens[idx-1] = (task := Command(tokens[idx-1]))
                    task.plane = 'bg'
                    
        except Exception as error:
            write(1, f'unkown error: {error}\n')
        return [token for token in tokens if isinstance(token, Command)]

    def sanitize(self, token):
        invalids = ('\t', ' ')
        for purge in invalids:
            token = ''.join(token.split(purge))
        return token


class Command(object):
    def __init__(self, line, support_evars=True):

        # Glorified move constructor
        if isinstance(line, Command):
            self.args = line.args
            self.iomap = line.iomap
            self.name = line.name
            self.plane = line.plane
            del(line)
            return
            
        tokens = line.split('\n')[0].split(' ')
        self.args = tokens
        self.iomap = []
        self.sanitize()
        self.plane = 'fg'

        if support_evars:
            self.expand_tokens()

        self.name = self.args[0]

    def exec(self, jobs):
        '''Fork and replace process in memory.
        Wrapper around exec libc call (for preprocessing hooks).'''
      
        # Try to execute binary
        pid = os.fork()
        if not pid:
            try:
                for config in self.iomap:
                    os.dup2(*config)
                os.execve(self.in_env(), self.args, os.environ)
            except OSError as error:
                os.write(1, f'OSError: {error}\n')
            sys.exit(1)
        
        try:
            for config in self.iomap:
                os.close(config[0])

            if self.plane == 'fg':
                _pid, status = os.waitpid(pid, 0)
                if status:
                    os.write(1, f'{self}: returned with exit code {status}\n'.encode())
                return

            jid = len(jobs) + 1
            for nil in range(60000):
                nil + 1
            os.waitpid(pid, os.WNOHANG)
            try:
                os.kill(pid, 0)
                jobs += [(jid, pid, self.name)]
            except:
                os.write(1, f'[{jid}] {pid} terminated {self.name}'.encode())
                
        except ChildProcessError as error:
            os.write(1, f'unknown error: {error}\n'.encode())
            
    def in_env(self):
        try:
            for base in reversed(os.environ['PATH'].split(':')):
                if self.name in os.listdir(base):
                    return base + '/' + self.name
        except KeyError:
            pass
        return None
    
    def expand_tokens(self):
        for idx,token in enumerate(self.args):
            if token[0] == '$':
                expansion = os.environ[token[1:]] if token[1:] in os.environ else ''
                self.args[idx] = expansion

    def can_execute(self):
        try:
            owner, group, mask = self.stat()
            exec_mask = [x % 2 for x in mask]
            if exec_mask[2]:
                return True
            if group in os.getgroups() and exec_mask[1]:
                return True
            if owner == os.getuid() and exec_mask[0]:
                return True
        except Exception:
            pass
        return False

    def stat(self):
        stat = os.stat(self.in_env())
        owner = stat.st_uid
        group = stat.st_gid
        mask = [int(x) for x in oct(stat.st_mode)[4:]]
        return owner, group, mask

    def sanitize(self):
        invalids = ('\t', ' ')
        for purge in invalids:
            for idx, token in enumerate(self.args):
                self.args[idx] = ''.join(token.split(purge))
        while '' in self.args:
            self.args.remove('')

    def __repr__(self):
        return 'Command: <' + ' '.join(self.args) + '>'

    def __str__(self):
        return repr(self)
        
                
class ReadlineFunctor(object):
    '''A *very* primitive readline implementation using
    a functor to simulate static allocation in a C module.'''
    def __init__(self, max_bytes=4, eof='', include_newline=True):
        self.exclusion_index = 0 if include_newline else 1
        self.max_bytes = max_bytes
        self.eof   = eof
        self.limit = 0
        self.idx   = 0
        self.buf   = ''

    def getchar(self):
        '''Construct a buffer from stdin, returning one character
        at a time.'''
        if self.idx == self.limit:
            self.buf   += read(0, self.max_bytes).decode()
            self.limit += len(self.buf[self.idx:])
        if not self.limit:
            return self.eof
        c = self.buf[self.idx]
        self.idx += 1
        return c

    def getline(self):
        '''Flush the character buffer and return the line.'''
        s = self.buf[:self.idx - self.exclusion_index]
        self.buf = self.buf[self.idx:]
        self.limit -= self.idx
        self.idx = 0
        return s
    
    def __call__(self, prompt=''):
        '''Simulate a call to readline.'''
        write(1, prompt.encode())
        while (c := self.getchar()) not in ('\n', self.eof):
            pass
        return self.getline()


class AntiBuffer(object):
    def __init__(self):
        pass

    def __enter__(self):
        self.termconfig = termios.tcgetattr(sys.stdin)
        tty.setcbreak(sys.stdin)
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self.termconfig)
        
        
        
    
class InvalidPythonException(Exception):
    def __init__(*args, **kwargs):
        super.__init__(*args, **kwargs)

if __name__ == '__main__':
    BananaShell()()
